[tool.ruff]
line-length = 100
target-version = "py311"
extend-exclude = [
    "models",
]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "UP", # pyupgrade
]
ignore = [
    \"E501\", # line length handled by formatter
    \"B008\", # allow FastAPI Depends in params
]

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
skip-magic-trailing-comma = false
